### ISSUE TITLE
bug: Error message appears on the screen when 7 filters are closed

### ISSUE THREAD

**Issue by sevilayerkan** [acikkaynak/deprem-yardim-frontend#1191] opened 2023-02-22 19:36 UTC
## Bug Definition
After opening the page, when we turn off 7 different filters from the filters on the right, an error message appears on the screen.

-- Please add discord contact information
** discord username: `notDepresseDeveloper#0919`  **

For reproducing you can contact `Bilal Günaydın#9379` in dc

## Bug environment
Describe the environment produces the bug. For example:
rc.afetharita.com

## Describe how you are producing the bug step by step

1. Go to rc.afetharita.com
2. Click 7 different filter from right
3. Bug appears

## Expected Behaviour
A clear and short text to decribe the expected behaviour.

## Screen shots
![image](https://user-images.githubusercontent.com/22706692/220737758-dbb01535-8ff4-4d9e-b715-c33f20b18082.png)

## Desktop Information
- Operating System: Win11
- Browser: Google Chrome 
- Version: 110.0.5481.104

## Additional Context
Add any other context about the bug here

**Comment by oguzergul** [comment] 2023-02-22 20:26
this is not a bug. I am closing the issue. testers browser extension caused this bug

**Closed by oguzergul** 2023-02-22 20:26 UTC
Labels: bug, discussion, unchecked, test-failed
