### ISSUE TITLE
bug: When language dropdown is opened user can not interact with UI until dropdown dismissed

### ISSUE THREAD

**Issue by utkubenli** [acikkaynak/deprem-yardim-frontend#1107] opened 2023-02-20 23:20 UTC
## Bug Definition
When the user opens the language dropdown by clicking it, rest of the UI becomes unresponsive until the user selects one of the dropdown options from the language options. Upon clicking anywhere else dropdown does close and second click to a button is basically functional

-- Please add discord contact information
** discord username: @utkubenli#4662**

## Bug environment
rc.afetharita.com
## Describe how you are producing the bug step by step

1. Go to 'rc.afetharita.com'
2. Click on the 'language-dropdown' 
3. try to interact with rest of the page

## Expected Behaviour
If user clicks on a location marker or another button, the opened language dropdown should not be blocking the click

## Screen shots

https://www.hizliresim.com/893lvfh

https://video.hizliresim.com/eRUCmzq19tguvxY/watch

## Desktop Information
- Operating System: Win10
- Browser Chrome
- Version 1.48.167

## Additional Context
Add any other context about the bug here

**Comment by mertkaya1033** [comment] 2023-02-21 00:55
The intended behaviour is as follows: When you click on the language dropdown, you need to choose the language. In the case that you press/click outside the dropdown when it is open, it should close, allowing you to interact with the rest of the app.

It seems like this bug is more like intended behavior. Lmk if I misunderstood the issue @utkubenli

**Comment by usirin** [comment] 2023-02-21 01:02
closing this as this is an intended behavior of a dropdown component.

**Closed by usirin** 2023-02-21 01:02 UTC
Labels: bug, approved, desktop, p0, test-failed
