### ISSUE TITLE
bug: No action can be taken from the error view.

### ISSUE THREAD

**Issue by agitrubard** [acikkaynak/deprem-yardim-frontend#849] opened 2023-02-12 15:30 UTC
## Bug Definition
When clicked on markers in certain locations, an error view is displayed and no action can be taken except via the "Deprem Yardım" button. Can't go back, forward or return home.

**discord username: agitrubard#7048**

## Bug environment
afetharita.com

## Expected Behaviour
Just as it happens on the other views, the detail view should prompt and actions must not be restricted.

## Screen shots
![image](https://user-images.githubusercontent.com/61833677/218320167-8f54c02f-5116-405b-a56f-68430b96cd4e.png)

## Desktop Information
- Operating System: macOS Monterey v12.6.3
- Browser Safari
- Version 16.3

**Comment by nazdezar** [comment] 2023-02-12 17:59
Can you please provide more details on how we can reproduce this issue? @agitrubard

**Comment by agitrubard** [comment] 2023-02-12 18:39
@nazdezar I click this hotel icon, error page is visible but not working
![Screen Shot 2023-02-12 at 9 36 57 PM](https://user-images.githubusercontent.com/61833677/218330215-a2a779f2-ea1d-4645-b058-6f44e2146f3f.png)

**Comment by EmirBoyaci** [comment] 2023-02-12 19:42
I just tried with Safari, couldn't reproduce this issue. Closing for now, if it is reproducable please open again

**Closed by EmirBoyaci** 2023-02-12 19:42 UTC
Labels: bug, approved, waiting-test

**Comment by muratyilmaz743** [comment] 2023-02-12 19:49
@EmirBoyaci I think this is due to data object mismatch in some locations and is being taken care of under #883.

**Comment by EmirBoyaci** [comment] 2023-02-12 19:51
> @EmirBoyaci I think this is due to data object mismatch in some locations and is being taken care of under #883.

That's correct but what I understand from issue is that, "I cannot use buttons in error page".
