### ISSUE TITLE
bug/refactor: Options on the right take up most of the screen on mobile

### ISSUE THREAD

**Issue by sevilayerkan** [acikkaynak/deprem-yardim-frontend#729] opened 2023-02-10 22:45 UTC
### Refactor Request

-- fill in the line below:
** discord username: notDepresseDeveloper#0919 **

Is your refactor request pertaining to a problem? Please elaborate.

The options on the right cover a large part of the map on mobile devices, and even when the language option on the test side is added, almost a quarter of the screen is becoming unusable depending on the device. This can cause problems, especially on devices with small screens.

### Suggested solution

This can cause problems, especially on devices with small screens. We think it would be more beneficial to add a dropdown-like feature for that part. 

### Extra context

Problem test envirorment:
Operating System: Android
Browser : Chrome Version 110.0.5481.64
Device : Samsung SM-J33F

Here is couple screenshots for the problem I've mentioned:
![image](https://user-images.githubusercontent.com/22706692/218214591-23285402-d3a2-41c0-a7d2-4462b073bdd4.png)
![image](https://user-images.githubusercontent.com/22706692/218214594-e052ff22-5bc3-42ca-8174-50c7011590d9.png)

**Comment by nazdezar** [comment] 2023-02-11 00:56
@sevilayerkan I think this is a UX improvement but not a bug and should be addressed as such. Marking this as approved and should be assigned to dev for an update.

**Comment by DavutDurgun** [comment] 2023-02-11 09:56
I will start doing it. Do we have a UI? Are we going to do something ourselves?

**Closed** 2023-02-11 17:14 UTC
Labels: improvement, discussion, approved, tested, later
