### ISSUE TITLE
bug: Marker points and heatmap dissappear between zoom levels 

### ISSUE THREAD

**Issue by utkubenli** [acikkaynak/deprem-yardim-frontend#1129] opened 2023-02-21 00:21 UTC
## Bug Definition
While zooming in and out and also hitting scan button we are observing that markers and heatmaps for certain data points get lost. It does not appear to be getting grouped into another group. It is clearly disappearing on both markers and heatmaps

-- Please add discord contact information
** discord username: @utkubenli#4662**

## Bug environment
Describe the environment produces the bug. For example:
rc.afetharita.com

## Describe how you are producing the bug step by step

1. Go to '[rc.afetharita.com](https://rc.afetharita.com/?lat=36.14230889037484&lng=36.13549232482911&zoom=14&reasons=kurtarma)'
2. Click 'scan' button 
3. keep zooming in and out as well as hitting scan button. 
4. Bug appears

## Expected Behaviour
Data points should not dissappear. Heatmap is a good indicator a data is grouped or not and it is showing that the total numbers should change if they are grouped. (this does not appear to be the case)

## Screen shots
https://dosya.co/8t4dk189r3xw/2023-02-21_02-33-52.mkv.html
https://dosya.co/oc1260xu3lbn/tarama_tam_ekrana_göre_çalışmıyor,_alanı_genişletilebilir..mp4.html

## Desktop Information
- Operating System:  Win 10
- Browser  Brave

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

**Comment by utkubenli** [comment] 2023-02-21 00:23
https://user-images.githubusercontent.com/124810497/220217002-02e782f6-1ea9-4301-8809-845e3ad8ac0b.mp4

**Comment by sercanerhan** [comment] 2023-02-21 00:43
@utkubenli I couldn't verify this one. It should have been fixed. could you please retry?

**Comment by nazdezar** [comment] 2023-02-21 02:25
I am not able to reproduce this either.

**Comment by usirin** [comment] 2023-02-21 04:04
Closing it as we can't reproduce.

**Closed by usirin** 2023-02-21 04:04 UTC
Labels: bug, desktop, waiting-test
